### ISSUE TITLE
Ksyxis newest Version of the mod work not with Mixinbooter Mod on the Minecraft Forge 1.12.2 Version

### ISSUE THREAD

**Issue by Titoo8899** [VidTu/Ksyxis#12]
### Describe the bug

The Mod Crash then I play your mod with the Mod "MixinBooter" by Start of Minecraft Forge 1.12.2 with the newest Versions of your mod the MixinBooter and the newest Forge Version. I have from the Builder of the MixinBooter (Link: https://modrinth.com/mod/mixinbooter) Version 8.8 and the newest beta 8.9 test and the same answer give me your mod. Please check the Picture. The Mod "MixinBootstrap work with your mod fine but I play many Mods with the other Mixin Mod the "MixinBooter" and I hope you can fix the Problem.

![Bug with Mixinbooter](https://github.com/VidTu/Ksyxis/assets/42325138/859fef91-ae35-48a6-84a5-61fc8735ed78)

P.S. Minecraft give only a Exit Code 1 Error out.

### To Reproduce

1. Put the newest Versions of your mod and the MixinBooter in the Mod Folder
2. Start Minecraft Launcher
3. Start in the Minecraft Launcher the Forge 1.12.2 - 14.23.5.2860 Version
4. The Game begin to load but in 2 seconds later comes a massage (see Picture) with a Bug and the answer is a Crash of the game
5. Finish

### Minecraft Version

Forge 1.12.2 - 14.23.5.2860

### Checklist

- [X] I'm using the latest [mod version](https://modrinth.com/mod/ksyxis)
- [X] I'm using the latest [Fabric](https://fabricmc.net/use/)/[Forge](https://files.minecraftforge.net/)

**Comment by VidTu** [comment]
hi, please test [this build](https://github.com/VidTu/Ksyxis/actions/runs/7200808846).
(click on *Artifacts*, then open the downloaded zip with any archiver, inside there will be a JAR file of the mod)

**Comment by Titoo8899** [comment]
Hi, I have testet the new Build and now work the game with the MixinBooter Mod. Thanks for the build and you can bring out this version for all

**Comment by Titoo8899** [comment]
And thanks for the fast support this is nice and I love your mod so much

**Comment by VidTu** [comment]
fixed in c45a745 (release: `1.2.2`, 94ec0ee)
thank you
