### ISSUE TITLE
Ksyxis freezes world loading

### ISSUE THREAD

**Issue by ThatLittleCrab** [VidTu/Ksyxis#17]
Ksyxis is causing loading problems and deliberately states in logs that it causes problems for the latest version. Will there be a fix

**Comment by VidTu** [comment]
ksyxis __always__ states in logs that it *may* be a cause of your problems. (i.e. it prints this warning always, it doesn't know if it'll freeze or not, it just prints this warning for everyone that is having problems, like you)
it works just fine in fresh installation, so it might be a mod conflict, please share your mod list

**Comment by VidTu** [comment]
no response.
