### ISSUE TITLE
All versions but oldest crash on 1.20.1

### ISSUE THREAD

**Issue by Joshernoob** [VidTu/Ksyxis#19]
I have mutiple pack, 2 avtive 1 in the works with this mod in it and all of them I'm forced to use `Ksyxis-Forge1.17-1.1` . The other 3 versions crash on load every time.

Versions: Using latest forge version, as well as tried to use last 3 forge version

**Comment by VidTu** [comment]
Unable to reproduce.
https://github.com/VidTu/Ksyxis/assets/60929459/e5869c6f-1a2c-4ead-a1ca-17a4719a76dd

Please, share your mod list, crash logs, Java version and Forge version/build.

**Comment by Joshernoob** [comment]
Mod list to large to post around 400 mods as for the rest
Log: https://pastebin.com/jbvpmNQ6
Forge: lastest 47.2.20 (None Neo)
kysyxis: lastest Ksyxis-1.2.2

> Unable to reproduce. https://github.com/VidTu/Ksyxis/assets/60929459/e5869c6f-1a2c-4ead-a1ca-17a4719a76dd
> 
> Please, share your mod list, crash logs, Java version and Forge version/build.

**Comment by VidTu** [comment]
fastload and ksyxis are incompatble by design. you have to choose one of them

**Comment by Joshernoob** [comment]
> fastload and ksyxis are incompatble by design. you have to choose one of them

was bugged wishout fastload in pack, will remove but still won't change the fact the lastest versions won't work
