### ISSUE TITLE
Incompatible with Fast Load Reforged

### ISSUE THREAD

**Issue by xelotex** [VidTu/Ksyxis#24]
If you install Ksyxis and FastLoad and try to run the game, it will crash on startup. But if you manage to run the game (idk how i did it without it crashing, maybe is because of embeddium), if you try to load a world, the loading screen will get stuck at 0% forever.

Crash on startup logs:
[debug.log](https://github.com/VidTu/Ksyxis/files/15183020/debug.log)
[latest.log](https://github.com/VidTu/Ksyxis/files/15183021/latest.log)

World loading screen logs:
[debug.log](https://github.com/VidTu/Ksyxis/files/15183048/debug.log)
[latest.log](https://github.com/VidTu/Ksyxis/files/15183049/latest.log)

**Comment by xelotex** [comment]
![Captura de pantalla (159)](https://github.com/VidTu/Ksyxis/assets/70168682/c3bc2c0e-8703-4141-9198-fc2445ab6679)

^ This ^ is the mod list with which i managed to get the game running, but if you try to run the game with only Ksyxis and Fast Load installed, it crashes on startup.

**Comment by xelotex** [comment]
Wait, it is incompatible just because both mods do the same thing right?

**Comment by VidTu** [comment]
yes, fastload is feature-powered (and loads chunks in some other fast way iirc) and ksyxis is minimal and doesn't load spawn chunks at all.
