### ISSUE TITLE
Mod is being marked as a virus via BitDefender

### ISSUE THREAD

**Issue by Treazul** [VidTu/Ksyxis#25]
Upon running a modpack with this mod bitdefender has marked it as infected
The file D:\ATLauncher\instances\TerraFirmaGreg\mods\Ksyxis-1.2.2.jar is infected with Trojan.GenericKD.72678267 and was moved to quarantine. It is recommended that you run a System Scan to make sure your system is clean.

**Comment by Treazul** [comment]
k

**Comment by VidTu** [comment]
@Treazul either your specific JAR is infected, your PC is infected with something else or you're getting man-in-the-middle-attacked: https://www.virustotal.com/gui/file/8e97bb392718099d54377738a3501284eef98fbd54f6b46b4350fc9267ef4d47

**Comment by Treazul** [comment]
It's probably just a false positive. I've submitted the file to the av and
let them know

**Comment by Treazul** [comment]
Correction, it is a false positive.

**Comment by Treazul** [comment]
Scratch that.
I clicked "Reanalyse" on virus total and it's reporting
[image: image.png]

**Comment by VidTu** [comment]
for fs sake, what they don't like

**Comment by VidTu** [comment]
maybe they don't like the way it uses a lot of method injections like [here](https://github.com/VidTu/Ksyxis/blob/24e297078ab28a04d50187518317739f25d28e31/src/main/java/ru/vidtu/ksyxis/mixins/ServerLevelMixin.java#L61) for multiversion support

**Comment by VidTu** [comment]
what's funny, the latest [gh actions snapshot](https://github.com/VidTu/Ksyxis/actions/runs/8736657104) is not being detected (even [after reanalyzing](https://www.virustotal.com/gui/file/6adc7c2a85bf61d348f78e2db60e1f323df299f910767ce642e0bfec2bc53941?nocache=1)) by any vendor

**Comment by Dorrivix** [comment]
got this on mod version 1.2.2, the file extension isn't .jar, it's .bNIhAX

the full file my av shows is Ksyxis-1,2,2,jar.bNIhAX

**Comment by VidTu** [comment]
@Dorrivix it seems like your antimalware renames it

**Comment by Dorrivix** [comment]
it doesn't trigger with version 1.2.1

**Comment by VidTu** [comment]
well it also [doesn't](https://www.virustotal.com/gui/file/6adc7c2a85bf61d348f78e2db60e1f323df299f910767ce642e0bfec2bc53941?nocache=1) with 1.2.3-SNAPSHOT, you can reverse engineer 1.2.2 JAR and find nothing there. it was probably incorporated in some bigger malware (such as infected Minecraft modpack) and now antimalware flags it. i will not update JAR until I'll add 1.20.5 compat in a few days.

**Comment by VidTu** [comment]
hopefully [fixed](https://www.virustotal.com/gui/file/53fef57ee8188e6485beedb44d8fdb32a6ec27bdedf1359c6a010c3f21f9ad3f) in 1.3.0.

**Comment by VidTu** [comment]
BitDefender no longer flags 1.2.2 as infected, other vendors should follow shortly
