### ISSUE TITLE
Error loading class Warnings?

### ISSUE THREAD

**Issue by Sputchik** [VidTu/Ksyxis#29]
Launched on fabric 1.20.4 server

Got some time to figure out that it was Ksyxis exactly, and after laucnhing with ksyxis only, i get output which is in pinned log file, which makes it a bit harder to read logs, tho server starts normally :(

[server.log](https://github.com/user-attachments/files/15786217/server.log)

**Comment by ImPigTu** [comment]
Are you sure? Mod on server?

**Comment by VidTu** [comment]
unfortunately, this is an unavoidable consequence of the mod being multi-loader

**Comment by VidTu** [comment]
ok, this was [easier to fix](https://github.com/VidTu/Ksyxis/commit/26ac475204ca93f32f84b93ec2de8ef54e98a63b) than i thought. (my initial idea was to suppress logs by injecting into root log4j logger, this uses some mixin internals but shouldn't hard fail anyway)
