### ISSUE TITLE
1.20.1 Sculk Horde Conflict World Create

### ISSUE THREAD

**Issue by Krimatoria** [VidTu/Ksyxis#32]
https://github.com/TeamPeril/Sculk-Horde/issues/61 - See

**Comment by VidTu** [comment]
as mod's author declared that the chunk MUST be loaded at that time, it's probably incompatible

**Comment by Krimatoria** [comment]
> поскольку автор мода заявил, что чанк ДОЛЖЕН быть загружен в это время, он, вероятно, несовместим

Yes, they wrote about the incompatibility in the download and the fact that it is incorrigible, at least it seems to be from their side of the mod ( Sad
