### ISSUE TITLE
World stuck loading at 0%, making the map unaccessible

### ISSUE THREAD

**Issue by vinnyg0621** [VidTu/Ksyxis#33]
[latest.log](https://github.com/user-attachments/files/16229451/latest.log)

**Comment by VidTu** [comment]
probable incompatibility with canary, will need to check later

**Comment by Hedwig7s** [comment]
Same issue with the same mixin error from radium but it stayed stuck
Canary/Radium is likely not the cause

**Comment by VidTu** [comment]
unfortunately, i'm not able to reproduce the issue and the logs don't provide that much useful information. there's canary directly in the stacktrace, it works fine with canary and radium. other suspected mods include:
- everything related to sinytra
- modernfix
- starlight
- ferrite core

i've installed all of them and enabled the most aggressive and breaking optimizations, but the world loads just fine.
