### ISSUE TITLE
Ksyxis making it so mobs on lazy chunks don't count towards the mob cap

### ISSUE THREAD

**Issue by toninr** [VidTu/Ksyxis#36]
Ksyxis prevents the mob switch on my world from working. The 96 zombie villagers that are stored on mob switch dissapear from the f3 menu but when I dissable the mod they pop up agian. I'm unaware if it is a mod incopatibility causing the issue, so I'll leave a txt file with a mod list from my minecraft instace, I'm playing on Fabric 1.21
[New World 1.21.txt](https://github.com/user-attachments/files/16565854/New.World.1.21.txt)

**Comment by VidTu** [comment]
ksyxis fully disables spawn chunks, so yeah, it's a "feature", not a bug.
you have two options:
1. delete ksyxis mod and use "spawnChunkRadius" gamerule to control that.
2. use "/forceload" command to force-load chunks within the mob switch.

**Comment by toninr** [comment]
Sorry didn’t now that, thanks for clarifying.
