### ISSUE TITLE
[Bug] World loading/generating anim

### ISSUE THREAD

**Issue by lalamapaka** [VidTu/Ksyxis#4]
### Describe the bug

When I join a world the world loading animation is stuck at 0% (1.18.2 ur mc version thing doesn't mention it)

### To Reproduce

1. Launch
2. Create/Join singleplayer world
3. Observe

### Minecraft Version

Fabric 1.17.1

### Checklist

- [X] I'm using the latest [mod version](https://modrinth.com/mod/ksyxis)
- [X] I'm using the latest [Fabric](https://fabricmc.net/use/)/[Forge](https://files.minecraftforge.net/)

**Comment by VidTu** [comment]
I've just tested and it works just fine, looks like you have some conflicting mod, can you give me your list of mods?

**Comment by lalamapaka** [comment]
Eugh yes there are a lot of mods. Hope this helps 
![image](https://user-images.githubusercontent.com/75388592/172055636-bbe3040d-608f-47bf-a66e-f5a8c8998cc0.png)

**Comment by lalamapaka** [comment]
closed it by accindent

**Comment by VidTu** [comment]
How am I supposed to test compatibility for all these mods?...
![image](https://user-images.githubusercontent.com/60929459/172055921-54702572-d31b-40e2-84c3-38e0624c8783.png)

**Comment by lalamapaka** [comment]
Yes thats why i said there are a lot

**Comment by lalamapaka** [comment]
Do i need to export it so u can use it with the downloaded mods

**Comment by VidTu** [comment]
Welp, it would be nice.

**Comment by lalamapaka** [comment]
[Faster-Than-Light-1.1.11-curseforge.zip](https://github.com/VidTu/Ksyxis/files/8840167/Faster-Than-Light-1.1.11-curseforge.zip)
this is curse

**Comment by VidTu** [comment]
It works for me.

**Comment by lalamapaka** [comment]
Wait whaat weird for me it doesn’t. If i get on my pc i’ll send a short vid of it not working.

**Comment by lalamapaka** [comment]
This is what [I get](https://i.imgur.com/czSiQ81.mp4) couldn't fit it here because file size

**Comment by VidTu** [comment]
Oh, you're talking about that. I thought world loading screen was freezing indefinitely for you. That's not a bug and generally, removing world pre-generation is the main feature of this mod. The loading screen is shown to make this mod compatible with other (optimization) mods, so it doesn't break mods. (like #1 or #2)

**Comment by lalamapaka** [comment]
Oh thought i would be removed cause it removes the step. But I understand for compatibility, maybe you could change that screen for less confusion, but i get the decision.
