### ISSUE TITLE
[Question] Usage in Modpacks

### ISSUE THREAD

**Issue by NXTler** [VidTu/Ksyxis#42]
Greetings,
I'm currently working on a VulkanMod based performance Modpack and would like to include this particular mod as well. However, I haven't found any information about the usage in Modpacks in the description.
What am I allowed to do?

**Comment by VidTu** [comment]
hello. the source code (as well as the packaged JAR files) are distributed under the [MIT License](https://github.com/VidTu/Ksyxis/blob/main/LICENSE), therefore the distribution (and modification) is allowed in any modpacks. **i'm not a lawyer**, but yes, that means _you can freely include this mod in any modpacks_, including under a different license or the "All Rights Reserved" license.

a link back (in your modpack's readme) to mod's page would be appreciated, but is not strictly required.

**Comment by NXTler** [comment]
I planned putting each mod I used with their according developer into the credits, including a link to the developer's Modrinth page, like this:
![grafik](https://github.com/user-attachments/assets/042b6331-7d2b-43c7-91ef-609197a37099)
Would that be okay for you?

**Comment by VidTu** [comment]
sure 👍
