### ISSUE TITLE
[Bug] Doesn't work on 1.18.2

### ISSUE THREAD

**Issue by NewbieXvwu** [VidTu/Ksyxis#6]
### Describe the bug

The mod failed when trying to load mixin on 1.18.2.
Maybe it's because I installed other mods,but I don't know what mod caused that.
Sorry for bad English...

### To Reproduce

1.Launch the game.
2.Game crashed.

### Minecraft Version

Fabric 1.18.2

### Logs/Screenshots/Videos

[crash-2022-07-23_14.02.02-client.txt](https://github.com/VidTu/Ksyxis/files/9173197/crash-2022-07-23_14.02.02-client.txt)  [latest.log](https://github.com/VidTu/Ksyxis/files/9173198/latest.log)

### Checklist

- [X] I'm using the latest [mod version](https://modrinth.com/mod/ksyxis)
- [X] I'm using the latest [Fabric](https://fabricmc.net/use/)/[Forge](https://files.minecraftforge.net/)

**Comment by VidTu** [comment]
Not incompatible, but the mod C3H6N6O6 does the SAME THING as Ksyxis and MORE. So, basically, you don't need to install Ksyxis with that mod.
