### ISSUE TITLE
[Bug] doesn't support 1.19.2

### ISSUE THREAD

**Issue by SussyBob** [VidTu/Ksyxis#7]
### Describe the bug

-

### To Reproduce

1. Install the mod
2. Launch Minecraft
3. Crash

### Minecraft Version

Fabric 1.19.2

### Checklist

- [X] I'm using the latest [mod version](https://modrinth.com/mod/ksyxis)
- [X] I'm using the latest [Fabric](https://fabricmc.net/use/)/[Forge](https://files.minecraftforge.net/)

**Comment by VidTu** [comment]
It works just fine on Fabric 1.19.2, probably the mod is just incompatible with some of your mods.

**Comment by SussyBob** [comment]
Oh ok thank you, i'm gonna find the problem.
