### ISSUE TITLE
[Feature] Update to 1.19.2

### ISSUE THREAD

**Issue by ryleu** [VidTu/Ksyxis#8]
### Related problem

The latest version of Minecraft is 1.19.2, and ksyxis has no release on modrinth for that version.

### Describe the solution you'd like

A 1.19.2 release would be awesome.

**Comment by VidTu** [comment]
It should work just fine on 1.19.2.

**Comment by ryleu** [comment]
Yeah, but it isn't marked as such on Modrinth... could you update the release to reflect the fact that it works? The tool I'm using to generate my mod pack can't tell that it should work.

**Comment by VidTu** [comment]
Done.

**Comment by ryleu** [comment]
thanks!

**Comment by allanonmage** [comment]
> Yeah, but it isn't marked as such on Modrinth... could you update the release to reflect the fact that it works? The tool I'm using to generate my mod pack can't tell that it should work.

What tool are you using? Is it Moddermore?

**Comment by ryleu** [comment]
I'm using packwiz.
